apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-bundle
  labels:
    {{- include "oc-wlogin.labels" . | nindent 4 }}
data:
  ca-bundle.crt: |
{{ .Files.Get .Values.ocWloginCerts.caBundle | indent 8}}
