apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oc-wlogin.fullname" . }}
  labels:
    {{- include "oc-wlogin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oc-wlogin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oc-wlogin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OC_WLOGIN_CLIENT_ID
              value: {{ .Values.ocWloginClientId }}
            - name: OC_WLOGIN_CLIENT_SECRET
              value: {{ .Values.ocWloginClientSecret }}
            - name: OC_WLOGIN_AUTH_URL
              value: {{ .Values.ocWloginOauthUrls.authorize }}
            - name: OC_WLOGIN_TOKEN_URL
              value: {{ .Values.ocWloginOauthUrls.token }}
{{- if .Values.ocWloginCerts.tls }}
            - name: OC_WLOGIN_TLS_CERT
              value: /opt/tls/tls.crt
            - name: OC_WLOGIN_TLS_KEY
              value: /opt/tls/tls.key
{{- else }}
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "1"
{{- end }}
            - name: OC_WLOGIN_CA_BUNDLE
              value: /opt/ca/ca-bundle.crt
          volumeMounts:
{{- if .Values.ocWloginCerts.tls }}
            - mountPath: /opt/tls
              name: tls-certkey
{{ end }}
            - mountPath: /opt/ca
              name: ca-bundle
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.portName }}
{{- if .Values.ocWloginCerts.tls }}
              scheme: HTTPS
{{- else }}
              scheme: HTTP
{{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.portName }}
{{- if .Values.ocWloginCerts.tls }}
              scheme: HTTPS
{{- else }}
              scheme: HTTP
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{- if .Values.ocWloginCerts.tls }}
        - name: tls-certkey
          secret:
            defaultMode: 420
            secretName: tls-certkey
{{ end }}
        - name: ca-bundle
          configMap:
            defaultMode: 420
            name: ca-bundle
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
