{{- if .Values.route.enabled -}}
{{- $fullName := include "oc-wlogin.fullname" . -}}
{{- $svcPortName := .Values.service.portName -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "oc-wlogin.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.ocWloginUrl }}
  port:
    targetPort: {{ $svcPortName }}
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}
{{- end }}
